apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: production
type: Opaque
data:
  # Les valeurs doivent être encodées en base64 ; echo -n 'votre-mot-de-passe' | base64
  AZ_USER: bW9uX3VzZXI=